# Generated by Django 5.2.8 on 2025-11-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
