# Generated by Django 5.2.8 on 2025-11-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='pricechangelog',
            table='PriceChangeLog',
        ),
        migrations.AlterModelTable(
            name='pricerecord',
            table='PriceRecord',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
