# Generated by Django 5.2.8 on 2025-11-25 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_product_name_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerecord',
            name='barcode',
        ),
        migrations.AddField(
            model_name='pricerecord',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
        ),
    ]
